### PR TITLE
Update podspec to 1.4.0

### PR DESCRIPTION
**Pull request by pvzig**
Could you tag a release 1.4.0 from `stable` with the Swift 4 changes and push it to the CocoaPods trunk? Thanks!

### CODE REVIEW

**Comment by allenhuang** [comment]
+1 need to get a updated pod spec from CocoaPods trunk

**Comment by lightbow** [comment]
Agreed. It's confusing the readme says you can just ```pod 'Swifter', '1.4.0'``` but that won't work until it's in the specs repo (which is still at 1.3.3)

**Comment by pvzig** [comment]
I've changed the readme back to say `1.3.3` for the time being. I don't currently have permission to update the Cocoapod.

**Comment by lightbow** [comment]
Alternatively, wouldn't this work as intended in the meantime?
```pod 'Swifter', :git => 'https://github.com/httpswift/Swifter.git', :branch => 'stable', :tag => '1.4.0'```

**Comment by pvzig** [comment]
Yeah, you could target either the `stable` branch or the `1.4.0` tag in your Podfile to pull the latest.

**Pull request merged**
