### PR TITLE
Updated project file to Xcode 8 / Swift 2.3

### PR DESCRIPTION
**Pull request by bonkey**

### CODE REVIEW

**Comment by allen-zeng** [comment]
@glock45 can we please release this in 1.2.7? Much appreciated!

**Comment by brennanMKE** [comment]
It would be great to have dedicated branches for `swift-2.3` and `swift-3.0` while many are transitioning to Xcode 8 in the coming weeks and months. This tweet below shows a good way to manage this transition.

It may also make sense to also create a branch for `xcode-7` which allows it to be used for those who are not moving to Xcode 8 yet.

https://twitter.com/radexp/status/760197303047168000

**Comment by allen-zeng** [comment]
There isn't a need for a separate branch for swift 2.3, because the code within the project can already compile under Xcode 8. This change doesn't affect Xcode 7 because it will just ignore the new project settings that it knows nothing about. 

Swift 3 dedicated branch, however, seems like an inevitability

**Comment by brennanMKE** [comment]
What Xcode 8 just asked me to do today was to update the project settings for Swift 2.3 and it modified files in the Pods folder. If these Swift 2.3 settings could be set on a branch it would not be necessary.

You can see the changes here. The main change is the Build Setting for the Swift version. There also identifiers for the last Swift migration. Those may be the only difference since Swift 2.2 and 2.3 are generally compatible without any changes to the code.

`SWIFT_VERSION = 2.3;`

https://github.com/brennanMKE/TestServer/pull/1

**Comment by allen-zeng** [comment]
That's what I'm saying - what's required for swift 2.3 can just go into the master branch, because it won't break Xcode 7 compilation. So setting theses things are no longer necessary.

**Pull request merged**
